apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: virtual-kubelet
  name: virtual-kubelet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-kubelet
  template:
    metadata:
      labels:
        app: virtual-kubelet
    spec:
      automountServiceAccountToken: true
      serviceAccount: virtual-kubelet-sa
      containers:
      - image: virtual-kubelet:v1
        name: virtual-kubelet
        args:
          # 服务配置项
          - --provider=example-provider       #  provider名
          - --nodename=edgenode               # 边缘节点名
          - --kubeconfig=./config/config.yaml # 需要连接的kubeconfig配置